# Generated by Django 4.2.5 on 2023-09-23 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_customer_id_remove_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
